---
- name: Add Elastic GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elastic 8.x repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch
  template:
    src: elastic
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Elasticsearch

- name: Install Kibana
  apt:
    name: kibana
    state: present
  notify: Restart Kibana

- name: Configure Kibana
  template:
    src: kibana
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Kibana

- name: Enable and start Elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: restarted

- name: Enable and start Kibana
  systemd:
    name: kibana
    enabled: yes
    state: restarted