syntax on
set paste
set tabstop=4
set shiftwidth=4
set smarttab
set et
set ruler
set statusline=%<%f%h%m%r%=format=%{&fileformat}\ file=%{&fileencoding}\ enc=%{&encoding}\ %b\ 0x%B\ %l,%c%V\ %P
set mouse-=a
set hlsearch