---
# -------------------------------
# Role prometheus
prometheus_version: 2.53.3

# -------------------------------
# Role node_exporter
node_exporter_version: 1.9.0

# -------------------------------
# ROLE firewall
firewall_allowed_tcp_ports:
  - "22"
  - "9090"
  - "9100"
  - "9200"
  - "5601"