---
prometheus_version: []
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_install_dir: /opt/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_global:
  scrape_interval: 15s
  evaluation_interval: 15s